import 'package:flutter/material.dart';

import 'CardWidget.dart';
import 'Utilities/ColorTheme.dart';

class CardData{
  static List<Widget> cardItems = [
    const CardWidget(
      cardColor: ColorTheme.blackCard,
      shadowColor: ColorTheme.blackCardShadow,
      cardTextColor: ColorTheme.cardText,
      cardNumberBoxColor: ColorTheme.cardNumberBox,
      cardImagePath: 'assets/images/blackCard.png',
      description: "Scrumptious choco\nmocha cupcakes\nPack of 6",
      titleLine1: 'Assorted',
      titleLine2: 'Mocha Cupcakes',
      quantity: 2,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      buyButtonColor: ColorTheme.orangeCard,
      secondPageTitleLine1: 'Mocha',
      secondPageTitleLine2: 'Cupcakes',
    ),
    const CardWidget(
      cardColor: ColorTheme.whiteCard,
      cardColorOpacity: 0.4,
      shadowColor: ColorTheme.whiteCardShadow,
      cardTextColor: ColorTheme.cardText3,
      cardNumberBoxColor: ColorTheme.cardNumberBox2,
      cardDetailBoxColor: ColorTheme.whiteCardBox,
      cardImagePath: 'assets/images/whiteCard.png',
      description: "Intricate glass\nchandelier\nPack of 1",
      descriptionColor: ColorTheme.cardText3,
      titleLine1: 'Glass',
      titleLine2: 'Chandelier',
      quantity: 3,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      secondPageTitleLine1: 'Glass',
      secondPageTitleLine2: 'Chandelier',
    ),
    const CardWidget(
      cardColor: ColorTheme.orangeCard,
      shadowColor: ColorTheme.orangeCardShadow,
      cardTextColor: ColorTheme.cardText,
      cardNumberBoxColor: ColorTheme.cardNumberBox,
      cardImagePath: 'assets/images/orangeCard.png',
      description: "Fresh white & pink\nroses bouquet\nPack of 12",
      descriptionColor: ColorTheme.cardText,
      titleLine1: 'Bouquet',
      titleLine2: 'Mixed Roses',
      quantity: 1,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      secondPageTitleLine1: 'Mixed',
      secondPageTitleLine2: 'Roses',
    ),
    const CardWidget(
      cardColor: ColorTheme.blackCard,
      shadowColor: ColorTheme.blackCardShadow,
      cardTextColor: ColorTheme.cardText,
      cardNumberBoxColor: ColorTheme.cardNumberBox,
      cardImagePath: 'assets/images/blackCard.png',
      description: "Scrumptious choco\nmocha cupcakes\nPack of 6",
      titleLine1: 'Assorted',
      titleLine2: 'Mocha Cupcakes',
      quantity: 2,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      buyButtonColor: ColorTheme.orangeCard,
      secondPageTitleLine1: 'Mocha',
      secondPageTitleLine2: 'Cupcakes',
    ),
    const CardWidget(
      cardColor: ColorTheme.whiteCard,
      cardColorOpacity: 0.4,
      shadowColor: ColorTheme.whiteCardShadow,
      cardTextColor: ColorTheme.cardText3,
      cardNumberBoxColor: ColorTheme.cardNumberBox2,
      cardDetailBoxColor: ColorTheme.whiteCardBox,
      cardImagePath: 'assets/images/whiteCard.png',
      description: "Intricate glass\nchandelier\nPack of 1",
      descriptionColor: ColorTheme.cardText3,
      titleLine1: 'Glass',
      titleLine2: 'Chandelier',
      quantity: 3,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      secondPageTitleLine1: 'Glass',
      secondPageTitleLine2: 'Chandelier',
    ),
    const CardWidget(
      cardColor: ColorTheme.orangeCard,
      shadowColor: ColorTheme.orangeCardShadow,
      cardTextColor: ColorTheme.cardText,
      cardNumberBoxColor: ColorTheme.cardNumberBox,
      cardImagePath: 'assets/images/orangeCard.png',
      description: "Fresh white & pink\nroses bouquet\nPack of 12",
      descriptionColor: ColorTheme.cardText,
      titleLine1: 'Bouquet',
      titleLine2: 'Mixed Roses',
      quantity: 1,
      viewingText: '120+ viewing',
      boughtText: '50+ bought',
      secondPageText: "Handcrafted perfect blend of chocolate and coffee with plump of caramel madness to leave you crave for more this Diwali. Your friends & family deserve this assorted box of six cupcakes!",
      secondPageTitleLine1: 'Mixed',
      secondPageTitleLine2: 'Roses',
    ),
  ];
}